version: "3"
services:
  server:
    image: jetbrains/teamcity-server:latest
    ports:
      - "8111:8111"
    volumes:
      - ./volumes/teamcityServer/datadir:/data/teamcity_server/datadir
      - ./volumes/teamcityServer/logs:/opt/teamcity/logs
  agent:
    build: builds/agent
    volumes:
      - ./volumes/teamcityAgent/agent_conf:/data/teamcity_agent/conf
      - ./volumes/teamcityAgent/testcontainersconf:/home/buildagent/
    environment:
      - SERVER_URL=http://server:8111
      - DOCKER_IN_DOCKER=start
    privileged: true
  registry:
    image: registry:2.8.1
    ports:
      - "5000:5000"