version: "3"
services:
  traefik:
    image: traefik:v2.9
    command: 
     - "--api.insecure=true"
     - "--providers.docker"
     - "--entrypoints.web.address=:80" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "8080:8080"

  ELK-elasticsearch:
    image: docker.io/elastic/elasticsearch:7.16.3
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"

  ELK-logstash:
    image: docker.io/elastic/logstash:7.16.3
    volumes:
      - source: ./pipelines
        target: /usr/share/logstash/pipeline
        type: bind
    depends_on:
      - ELK-elasticsearch

  ELK-kibana:
    image: docker.io/elastic/kibana:7.16.3
    depends_on:
      - ELK-elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://ELK-elasticsearch:9200
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ELK-kibana.rule=Host(`elk.localhost`)"
      - "traefik.http.routers.ELK-kibana.entrypoints=web"

  Jaeger:
    image: jaegertracing/all-in-one:1.37.0
    ports:
      - "16686:16686"
      - "4318:4318"
    environment:
      COLLECTOR_OTLP_ENABLED: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.Jaeger.rule=Host(`jaeger.localhost`)"
      - "traefik.http.routers.Jaeger.entrypoints=web"
      - "traefik.http.services.Jaeger.loadbalancer.server.port=16686"

  dsa:
    build:
      context: ../dsa/
      dockerfile: ../dsa/src/main/docker/Dockerfile.jvm
    depends_on:
      - traefik
      - dsa-minio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dsa.rule=Host(`dsa.localhost`)"
      - "traefik.http.routers.dsa.entrypoints=web"
    environment:
      QUARKUS_MINIO_URL: http://dsa-minio:9000
      QUARKUS_MINIO_ACCESS_KEY: test_user
      QUARKUS_MINIO_SECRET_KEY: test_pass
      QUARKUS_ELASTICSEARCH_HOSTS: dsa-elastic:9200
  #    ports:
  #      - "8080:8080"
  dsa-minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: test_user
      MINIO_ROOT_PASSWORD: test_pass
    volumes:
      - data1-1:/data1
    command: server --console-address :9001 /data
    ports:
      - "9001:9001"

  dsa-elastic:
   image: elastic/elasticsearch:7.16.3
   environment:
     discovery.type: single-node



  mba:
    build:
      context: ../mba/
      dockerfile: ../mba/src/main/docker/Dockerfile.jvm
    depends_on:
      - traefik
      - mba_mongo
    labels:
      - "traefik.http.routers.mba.rule=Host(`mba.localhost`)"
    environment:
      QUARKUS_MONGODB_HOSTS: mba_mongo
      QUARKUS_MONGODB_DATABASE: default

  mba_mongo:
    image: mongo:5.0

  math:
    build:
      context: ../math/
      dockerfile: ../math/src/main/docker/Dockerfile.jvm
    depends_on:
      - traefik
    labels:
      - "traefik.http.routers.math.rule=Host(`math.localhost`)"

volumes:
  data1-1:
